function C = loadDatalogFiles()
%
%This function reads data files generated by ST's STWIN via its High Speed Datalog application.
%
%usage:  C = loadDatalogFiles()
%
%acquisition folder and files are selected via GUI.
%	C = nx2 Matlab Cell Array, where n = number of files selected
%   C{i, [data, time]} = array with sample data and time from the i-th selected file. 
%     data is a [n, m] array, 
%     time is a [1, m] array. 
%   where:
%     n = number of sensor axes, m = number of samples
%

    [fJ,fpath] = uigetfile('*.dat','Select one or more STWIN sensors data logs','MultiSelect','on');

    if iscell(fJ)
        filenames = strings(1, length(fJ));
        for k = 1:length(fJ)
            filenames(k) = cell2mat(fJ(k));
        end
    else
        filenames = strings(1, 1);
        filenames(1) = fJ;
    end

    num_files = length(filenames);
    
    configJSONFileName = 'DeviceConfig.json';
    acquisitonJSONFileName = 'AcquisitionInfo.json';

    cjson = get_jsonFile(configJSONFileName, fpath);
    % ajson = get_jsonFile(acquisitonJSONFileName, fpath);

    C = cell(num_files, 2);
    
    for ii = 1:num_files
        [d, t] = get_subsensorData(cjson, filenames(ii), fpath);
        C(ii, :) = {d, t};
    end

end

function fjson = get_jsonFile(fileJSON, fpath)
    fullName = strcat(fpath, fileJSON);
    fid = fopen(fullName);
    str = fread(fid,inf);
    fclose(fid);
    fjson = jsondecode(char(str)');
end

function type = checkType(type)

switch type
    case 'uint8_t'
        type = 'uint8';
    case 'uint16_t'
        type = 'uint16';
    case 'uint32_t'
        type = 'uint32';
    case 'int8_t'
        type = 'int8';
    case 'int16_t'
        type = 'int16';
    case 'int32_t'
        type = 'int32';
    case 'float'
        type = 'single';
    case 'double'
        type = 'double';
end

end

function typeLength = checkTypeLength(type)

switch type
    case {'uint8_t','int8_t'}
        typeLength = 1;
    case {'uint16_t','int16_t'}
        typeLength = 2;
    case {'uint32_t','int32_t'}
        typeLength = 4;
    case 'float'
        typeLength = 4;
    case 'double'
        typeLength = 8;
end

end
